package pl.rutkowski.bandcollection;

public enum Genre {

    BLACK, DEATH, DOOM, STONER, SLUDGE, ELECTRONIC, INDUSTRIAL, EXPERIMENTAL, AVANT_GARDE, FOLK, VIKING, PAGAN,
    GOTHIC, GRINDCORE, GROOVE, HEAVY, METALCORE, DEATHCORE, POWER, PROGRESSIVE, SPEED, SYMPHONIC, THRASH, OTHER

}
